on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Golang Test Annotations
      # You may pin to the exact commit or the version.
      # uses: guyarb/golang-test-annotations@fe8ce93f39326426b42a8ecc8eac22a33f6ee241
      uses: guyarb/golang-test-annotations@v0.3.0
      with:
        # The path of the go test results
        test-results: test.json
